# Generated by Django 4.1 on 2022-08-16 08:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AudiAndVideo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField()),
            ],
            options={
                'verbose_name': 'Аудио и видео',
                'verbose_name_plural': 'Аудио и видео',
            },
        ),
        migrations.CreateModel(
            name='Battery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField()),
            ],
            options={
                'verbose_name': 'Аккумулятор',
                'verbose_name_plural': 'Аккумуляторы',
            },
        ),
        migrations.CreateModel(
            name='Camera',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField()),
            ],
            options={
                'verbose_name': 'Камера',
                'verbose_name_plural': 'Камеры',
            },
        ),
        migrations.CreateModel(
            name='ComputingResources',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField()),
            ],
            options={
                'verbose_name': 'Вычислительные ресурсы',
                'verbose_name_plural': 'Вычислительные ресурсы',
            },
        ),
        migrations.CreateModel(
            name='ContentsOfDelivery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField()),
            ],
            options={
                'verbose_name': 'Комплект поставки',
                'verbose_name_plural': 'Комплекты поставки',
            },
        ),
        migrations.CreateModel(
            name='DimensionsAndWeight',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField()),
            ],
            options={
                'verbose_name': 'Размеры и вес',
                'verbose_name_plural': 'Размеры и вес',
            },
        ),
        migrations.CreateModel(
            name='Display',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField()),
            ],
            options={
                'verbose_name': 'Дисплей',
                'verbose_name_plural': 'Дисплеи',
            },
        ),
        migrations.CreateModel(
            name='DisplayAndBody',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField()),
            ],
            options={
                'verbose_name': 'Дисплей и корпус',
                'verbose_name_plural': 'Дисплеи и корпусы',
            },
        ),
        migrations.CreateModel(
            name='NetworkSupport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField()),
            ],
            options={
                'verbose_name': 'Поддержка сетей',
                'verbose_name_plural': 'Поддержки сетей',
            },
        ),
        migrations.CreateModel(
            name='SecureAuthentication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField()),
            ],
            options={
                'verbose_name': 'Безопасная аутентификация',
                'verbose_name_plural': 'Безопасная аутентификация',
            },
        ),
        migrations.CreateModel(
            name='WaterAndDustProtection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField()),
            ],
            options={
                'verbose_name': 'Защита от воды и пыли',
                'verbose_name_plural': 'Защита от воды и пыли',
            },
        ),
    ]
