# Generated by Django 4.1 on 2022-08-16 08:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('characteristic_app', '0001_initial'),
        ('core_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='phone',
            name='audi_and_video',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='characteristic_app.audiandvideo', verbose_name='Аудио и видео'),
        ),
        migrations.AlterField(
            model_name='phone',
            name='battery',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='characteristic_app.battery', verbose_name='Аккумулятор'),
        ),
        migrations.AlterField(
            model_name='phone',
            name='camera',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='characteristic_app.camera', verbose_name='Камера'),
        ),
        migrations.AlterField(
            model_name='phone',
            name='computing_resources',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='characteristic_app.computingresources', verbose_name='Вычислительные ресурсы'),
        ),
        migrations.AlterField(
            model_name='phone',
            name='contents_of_delivery',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='characteristic_app.contentsofdelivery', verbose_name='Комплект поставки'),
        ),
        migrations.AlterField(
            model_name='phone',
            name='dimensions_and_weight',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='characteristic_app.dimensionsandweight', verbose_name='Размеры и вес'),
        ),
        migrations.AlterField(
            model_name='phone',
            name='display',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='characteristic_app.display', verbose_name='Дисплей'),
        ),
        migrations.AlterField(
            model_name='phone',
            name='display_and_body',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='characteristic_app.displayandbody', verbose_name='Дисплей и корпус'),
        ),
        migrations.AlterField(
            model_name='phone',
            name='network_support',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='characteristic_app.networksupport', verbose_name='Поддержка сетей'),
        ),
        migrations.AlterField(
            model_name='phone',
            name='secure_authentication',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='characteristic_app.secureauthentication', verbose_name='Безопасная аутентификация'),
        ),
        migrations.AlterField(
            model_name='phone',
            name='water_and_dust_protection',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='characteristic_app.wateranddustprotection', verbose_name='Защита от воды и пыли'),
        ),
        migrations.DeleteModel(
            name='AudiAndVideo',
        ),
        migrations.DeleteModel(
            name='Battery',
        ),
        migrations.DeleteModel(
            name='Camera',
        ),
        migrations.DeleteModel(
            name='ComputingResources',
        ),
        migrations.DeleteModel(
            name='ContentsOfDelivery',
        ),
        migrations.DeleteModel(
            name='DimensionsAndWeight',
        ),
        migrations.DeleteModel(
            name='Display',
        ),
        migrations.DeleteModel(
            name='DisplayAndBody',
        ),
        migrations.DeleteModel(
            name='NetworkSupport',
        ),
        migrations.DeleteModel(
            name='SecureAuthentication',
        ),
        migrations.DeleteModel(
            name='WaterAndDustProtection',
        ),
    ]
