# Generated by Django 4.1 on 2022-08-23 06:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core_app', '0002_alter_phone_audi_and_video_alter_phone_battery_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='phone',
            name='image',
        ),
        migrations.CreateModel(
            name='PhoneImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='', verbose_name='Фото')),
                ('image_link', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='image', to='core_app.phone', verbose_name='Ссылка на объект')),
            ],
            options={
                'verbose_name': 'Фото объекта',
                'verbose_name_plural': 'Фото объекта',
            },
        ),
    ]
